language: python
jobs:
  include:
    - name: "Python 3.8 on Xenial Linux"
      python: 3.8
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7
    - name: "Python 3.8 on Xenial Linux"
      python: 3.6
env: PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR/avro_validator
install:
  "pip install -r requirements.txt"
script:
  pytest avro_validator/tests --cov=avro_validator && flake8 avro_validator
after_success:
  coveralls
